/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function main(): void;
export function ping(a: number, b: number): void;
export function load_font(a: number): void;
export function set_doc(a: number, b: number, c: number, d: number, e: number, f: number, g: number): void;
export function set_section(a: number, b: number): void;
export function set_source(a: number, b: number, c: number, d: number): void;
export function build_tree(a: number): void;
export function draw_doc(a: number, b: number, c: number, d: number, e: number): void;
export function resize(a: number, b: number, c: number, d: number): void;
export function tab_change(a: number, b: number, c: number, d: number, e: number): void;
export function get_section(): number;
export function touch_start(a: number, b: number, c: number): void;
export function touch_move(a: number, b: number, c: number): void;
export function touch_end(a: number): void;
export function single_click(a: number, b: number, c: number): void;
export function double_click(a: number, b: number, c: number): void;
export function mode_change(a: number, b: number): void;
export function tool_func(a: number, b: number): void;
export function hide(a: number, b: number): void;
export function stroke_back(a: number): void;
export function stroke_clear(a: number): void;
export function __wbindgen_malloc(a: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number): number;
export const __wbindgen_export_2: WebAssembly.Table;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__hf4f0a00cfef81533(a: number, b: number, c: number): void;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_exn_store(a: number): void;
export function __wbindgen_start(): void;
